version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Medi.Server/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=MediDB;User=mediuser;Password=medipass;
    depends_on:
      db:
        condition: service_healthy 

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: mediuser
      MYSQL_PASSWORD: medipass
      MYSQL_DATABASE: MediDB
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
